# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73621733e39a6bcb72469f4d198b58d8fe58d29584163379a040aed08abd845091ef9c73bac6d5fb0e4610522ceaf1afa89e39e6ee147c22b09bc38d6b172300

test:
  secret_key_base: 65c55cac17c69ebc94ddec3cac5fb4641cfa14d9ca1a521091bf518451e3791a9e5898477ff5062dedef98703e2e8a088796c2bb35cdc9a26a2954ddd34813e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
